// Categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
export const CLEAN_FORM_ADD_CATEGORY = 'CLEAN_FORM_ADD_CATEGORY';

// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FILTER_SUCCESS = 'GET_PRODUCTS_FILTER_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CLEAN_FORM_ADD_PRODUCT = 'CLEAN_FORM_ADD_PRODUCT';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

// Filtros
export const ADD_FILTER_CATEGORY = 'ADD_FILTER_CATEGORY'
export const REMOVE_FILTER_CATEGORY = 'REMOVE_FILTER_CATEGORY'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

export const ADD_FILTER_PRICE = 'ADD_FILTER_PRICE'
export const REMOVE_FILTER_PRICE = 'REMOVE_FILTER_PRICE';

export const FILTER_SEARCH = 'FILTER_SEARCH';
export const REMOVE_FILTER_SEARCH = 'REMOVE_FILTER_SEARCH';

// Checkout
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const REPLACE_TO_CART = 'REPLACE_TO_CART'
export const HANDLE_CHANGE_DATA = 'HANDLE_CHANGE_DATA';

export const CLEAN_CHECKOUT_SUCCESS = 'CLEAN_CHECKOUT_SUCCESS';

// Checkout - cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS'
export const ADD_PRODUCT_TO_CART_ERROR = 'ADD_PRODUCT_TO_CART_ERROR';
export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_TO_CART_SUCCESS = 'REMOVE_PRODUCT_TO_CART_SUCCESS';
export const REMOVE_PRODUCT_TO_CART_ERROR = 'REMOVE_PRODUCT_TO_CART_ERROR';
export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_ERROR  = 'GET_CART_ERROR';
export const CLEAN_CHECKOUT = 'CLEAN_CHECKOUT';

export const SET_CHECKOUT_DATA = 'SET_CHECKOUT_DATA';

export const CHECKOUT = 'CHECKOUT';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR';

export const SET_SHIPPING_COST = 'SET_SHIPPING_COST';

export const SET_VIEW_CART_GLOBAL = 'SET_VIEW_CART_GLOBAL';

// Login
export const NEW_ACCOUNT = 'NEW_ACCOUNT';
export const NEW_ACCOUNT_SUCCESS = 'NEW_ACCOUNT_SUCCESS';
export const NEW_ACCOUNT_ERROR = 'NEW_ACCOUNT_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const GET_USER = 'GET_USER';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const SET_VERIFY = 'SET_VERIFY';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';

export const ACCOUNT_VALIDATED = 'ACCOUNT_VALIDATED';
export const ACCOUNT_VALIDATED_SUCCESS = 'ACCOUNT_VALIDATED_SUCCESS';
export const ACCOUNT_VALIDATED_ERROR = 'ACCOUNT_VALIDATED_ERROR'; 

// Admin
export const CHANGE_CONTENT = 'CHANGE_CONTENT';

// Tag
export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';

// Orders 
export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';

// Newsletter
export const CREATE_NEWSLETTER = 'CREATE_NEWSLETTER';
export const CREATE_NEWSLETTER_SUCCESS = 'CREATE_NEWSLETTER_SUCCESS';
export const CREATE_NEWSLETTER_ERROR = 'CREATE_NEWSLETTER_ERROR';

export const CREATE_CONTACT = 'CREACT_CONTACT';
export const CREATE_CONTACT_SUCCESS = 'CREACT_CONTACT_SUCCESS';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';
